package br.edu.ifpr.sistemadenotas.telas;

import br.edu.ifpr.sistemadenotas.estilizacao.CpfUtils;
import br.edu.ifpr.sistemadenotas.modelo.AuxiliarAdministrativo;
import br.edu.ifpr.sistemadenotas.operacoes.OperacoesNotas;
import br.edu.ifpr.sistemadenotas.telas.RecuperacaoSenha;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCpf = new javax.swing.JLabel();
        txtCpf = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        lblImgCadeado = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnEsqueceuSenha = new javax.swing.JButton();
        lblResposta = new javax.swing.JLabel();
        lblImgTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ICMS/NOTAS");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(516, 440));
        setResizable(false);
        getContentPane().setLayout(null);

        lblCpf.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblCpf.setForeground(new java.awt.Color(102, 153, 255));
        lblCpf.setText("CPF ou Chave:");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(110, 140, 270, 16);

        txtCpf.setToolTipText("Informe o cpf com esssa estrutura 000.000.000-00");
        txtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfActionPerformed(evt);
            }
        });
        txtCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCpfKeyReleased(evt);
            }
        });
        getContentPane().add(txtCpf);
        txtCpf.setBounds(110, 160, 270, 22);

        lblSenha.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(102, 153, 255));
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha);
        lblSenha.setBounds(110, 200, 270, 16);

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha);
        txtSenha.setBounds(110, 220, 270, 22);

        lblImgCadeado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bloqueado (1).png"))); // NOI18N
        lblImgCadeado.setText("jLabel2");
        getContentPane().add(lblImgCadeado);
        lblImgCadeado.setBounds(220, 70, 60, 60);

        btnCadastrar.setText("Criar conta");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(192, 280, 100, 23);

        btnLogin.setText("Logar");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(300, 280, 72, 23);

        btnEsqueceuSenha.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        btnEsqueceuSenha.setForeground(new java.awt.Color(102, 153, 255));
        btnEsqueceuSenha.setText("Esqueceu a senha?");
        btnEsqueceuSenha.setBorder(null);
        btnEsqueceuSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsqueceuSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnEsqueceuSenha);
        btnEsqueceuSenha.setBounds(260, 240, 140, 16);

        lblResposta.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(lblResposta);
        lblResposta.setBounds(120, 250, 190, 30);

        lblImgTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/[500, 400](4).png"))); // NOI18N
        lblImgTela.setText("jLabel1");
        getContentPane().add(lblImgTela);
        lblImgTela.setBounds(0, 0, 541, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        this.dispose(); // Fecha a tela de login
        new CadastrarConta().setVisible(true); // Abre a tela de cadastro

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtCpfActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtSenhaActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnLoginActionPerformed
        AuxiliarAdministrativo auxiliar = new AuxiliarAdministrativo();
        String cpf = txtCpf.getText();
        auxiliar.setCpf(cpf);
        String senha = new String(txtSenha.getText());
        auxiliar.setSenha(senha);

        // Valida o usuário
        if (OperacoesNotas.validarUsuario(auxiliar)) {
            JOptionPane.showMessageDialog(this, "Login bem-sucedido!");
            this.dispose(); // Fecha a tela de login
            new MenuSistema().setVisible(true); // Abre a tela do menu
        } else {
            lblResposta.setText("CPF ou senha incorretos!");
        }

    }// GEN-LAST:event_btnLoginActionPerformed

    private void btnEsqueceuSenhaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnEsqueceuSenhaActionPerformed
        btnEsqueceuSenha.setBorderPainted(false); // Remove a borda
        btnEsqueceuSenha.setContentAreaFilled(false); // Remove o fundo do botão
        btnEsqueceuSenha.setFocusPainted(false); // Remove a borda de foco
        btnEsqueceuSenha.setOpaque(false);
        btnEsqueceuSenha.setOpaque(false); // Torna o botão transparente
        // Fecha a janela atual de Login
        this.dispose();

        // Cria uma nova instância da tela de recuperação de senha e a exibe
        RecuperacaoSenha telaRecuperacao = new RecuperacaoSenha();
        telaRecuperacao.setVisible(true);
    }// GEN-LAST:event_btnEsqueceuSenhaActionPerformed

    private void txtCpfKeyReleased(java.awt.event.KeyEvent evt) {
        String cpf = txtCpf.getText();
        txtCpf.setText(CpfUtils.formatarCpf(cpf));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEsqueceuSenha;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblImgCadeado;
    private javax.swing.JLabel lblImgTela;
    private javax.swing.JLabel lblResposta;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
