/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.sistemadenotas.telas;

import br.edu.ifpr.sistemadenotas.modelo.Notas;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Aluno
 */
public class MenuSistema extends javax.swing.JFrame {

    private List<Notas> notas; // Lista de notas
    private TabelaNotas listaNotasTela; // Tela de lista de notas

     public MenuSistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrar = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnDesconectar = new javax.swing.JButton();
        lblImgTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu do Sistema");
        setMaximumSize(new java.awt.Dimension(510, 440));
        setMinimumSize(new java.awt.Dimension(505, 433));
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        btnCadastrar.setBackground(new java.awt.Color(102, 204, 255));
        btnCadastrar.setText("Cadastrar Nota");
        btnCadastrar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCadastrar);
        btnCadastrar.setBounds(70, 140, 130, 30);

        btnLista.setBackground(new java.awt.Color(102, 204, 255));
        btnLista.setText("Lista de Notas");
        btnLista.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLista);
        btnLista.setBounds(300, 140, 140, 30);

        btnDesconectar.setBackground(new java.awt.Color(102, 204, 255));
        btnDesconectar.setText("Desconectar");
        btnDesconectar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesconectarActionPerformed(evt);
            }
        });
        getContentPane().add(btnDesconectar);
        btnDesconectar.setBounds(180, 210, 140, 30);

        lblImgTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Cópia de AREA Ad.png"))); // NOI18N
        getContentPane().add(lblImgTela);
        lblImgTela.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        this.dispose();  // Fecha a tela de cadastro
        CadastrarNotas cadastroNota = new CadastrarNotas(notas); // Passa a lista de notas existente
        cadastroNota.setVisible(true); // Exibe a tela de cadastro
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        this.dispose(); // Fecha o menu
        TabelaNotas listaNotasTela = new TabelaNotas(); // Cria a tela de lista de notas
        listaNotasTela.setVisible(true); // Exibe a tela de lista de notas
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesconectarActionPerformed
        // Fecha a tela de recuperação de senha e volta para a tela de login
        this.dispose();
        new Login().setVisible(true); // Assumindo que TelaLogin é a tela de login
    }//GEN-LAST:event_btnDesconectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSistema().setVisible(true); // Inicia o menu
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDesconectar;
    private javax.swing.JButton btnLista;
    private javax.swing.JLabel lblImgTela;
    // End of variables declaration//GEN-END:variables
}
