/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifpr.sistemadenotas.telas;

import br.edu.ifpr.sistemadenotas.modelo.AuxiliarAdministrativo;
import javax.swing.JOptionPane;

/**
 *
 * @author Aluno
 */
public class RecuperacaoSenha extends javax.swing.JFrame {



    /**
     * Creates new form RecuperacaoSenha
     */
    public RecuperacaoSenha() {
        initComponents();
        configurarBotoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnProsseguir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblImgTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recuperação de Senha");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(516, 431));
        setMinimumSize(new java.awt.Dimension(516, 431));
        setPreferredSize(new java.awt.Dimension(516, 431));
        getContentPane().setLayout(null);

        lblEmail.setText("Email:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(27, 135, 50, 16);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        getContentPane().add(txtEmail);
        txtEmail.setBounds(71, 132, 304, 22);

        btnProsseguir.setText("Prosseguir");
        btnProsseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsseguirActionPerformed(evt);
            }
        });
        getContentPane().add(btnProsseguir);
        btnProsseguir.setBounds(265, 230, 100, 23);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(105, 230, 100, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Informe seu E-mail para recuperar ou redefinir sua senha:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 100, 350, 16);

        lblImgTela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/RECUPERAÇÃO DE SENHA.png"))); // NOI18N
        getContentPane().add(lblImgTela);
        lblImgTela.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Fecha a tela de recuperação de senha e volta para a tela de login
        this.dispose();
        new Login().setVisible(true); // Assumindo que TelaLogin é a tela de login
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsseguirActionPerformed
        String email = txtEmail.getText().trim();

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira seu e-mail.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;    }//GEN-LAST:event_btnProsseguirActionPerformed
    }

    private void txtCpfActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtCpfActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtCpfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperacaoSenha.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperacaoSenha.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperacaoSenha.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperacaoSenha.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecuperacaoSenha().setVisible(true);
            }
        });
    }

    public class TelaRecuperacaoSenha extends javax.swing.JFrame {

        // Constructor
        public TelaRecuperacaoSenha() {
            initComponents();
        }

        private void btnEnviarCodigoActionPerformed(java.awt.event.ActionEvent evt) {
            String cpfOuEmail = txtEmail.getText().trim();

            if (cpfOuEmail.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, insira seu CPF ou e-mail.", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Lógica para verificar o CPF ou e-mail no banco de dados
            if (verificarUsuario(cpfOuEmail)) {
                // Enviar código de recuperação ou link para e-mail cadastrado
                enviarCodigoOuLink(cpfOuEmail);
                JOptionPane.showMessageDialog(this, "Um link de recuperação foi enviado para seu e-mail.", "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Usuário não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }

        private boolean verificarUsuario(String cpfOuEmail) {
            // Aqui você vai consultar seu banco de dados para verificar se o CPF ou e-mail
            // existe
            // Simulando um caso de sucesso (você deve substituir isso pela verificação
            // real)
            return cpfOuEmail.equals("usuario@exemplo.com") || cpfOuEmail.equals("123.456.789-00");
        }

        private void enviarCodigoOuLink(String cpfOuEmail) {
            // Lógica para enviar o link de recuperação por e-mail ou SMS
            // Aqui você vai precisar de integração com um serviço de envio de e-mails (como
            // JavaMail) ou API de SMS
            String linkRecuperacao = "http://www.seusite.com/redefinir-senha?usuario=" + cpfOuEmail;
            // Simulação de envio
            System.out.println("Enviando link de recuperação para: " + cpfOuEmail);
            System.out.println("Link de recuperação: " + linkRecuperacao);
            // Você deveria integrar isso com um serviço de e-mail ou SMS real.
        }
    }

    // Dentro da classe RecuperacaoSenha
    private void configurarBotoes() {
        btnCancelar = new javax.swing.JButton("Cancelar");
        btnCancelar.addActionListener(evt -> btnCancelarActionPerformed(evt));
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(110, 200, 100, 25);

        btnProsseguir = new javax.swing.JButton("Prosseguir");
        btnProsseguir.addActionListener(evt -> btnProsseguirActionPerformed(evt));
        getContentPane().add(btnProsseguir);
        btnProsseguir.setBounds(220, 200, 100, 25);
    }

    private void btnProsseguiActionPerformed(java.awt.event.ActionEvent evt) {
        String email = txtEmail.getText().trim();

        if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, insira seu e-mail.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verifica o e-mail no banco de dados e envia o código
        if (verificarUsuario(email)) {
            enviarCodigoOuLink(email);
            JOptionPane.showMessageDialog(this, "Um link de recuperação foi enviado para seu e-mail.", "Sucesso",
                    JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Fecha a tela de recuperação de senha
            new RecuperacaoSenha().setVisible(true); // Assumindo que RedefinicaoSenha é a tela de redefinição
        } else {
            JOptionPane.showMessageDialog(this, "E-mail não encontrado.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Verifica se o usuário (CPF ou E-mail) está cadastrado no sistema
    private boolean verificarUsuario(String cpfOuEmail) {
        // Simulação de consulta no banco de dados
        // Substitua essa lógica com a verificação real no seu banco de dados
        return cpfOuEmail.equals("usuario@exemplo.com") || cpfOuEmail.equals("123.456.789-00");
    }

    // Envia o link de recuperação de senha para o e-mail cadastrado
    private void enviarCodigoOuLink(String cpfOuEmail) {
        // Geração de um link de recuperação (simulado)
        String linkRecuperacao = "http://www.seusite.com/redefinir-senha?usuario=" + cpfOuEmail;

        // Exibindo no console (simulação do envio)
        System.out.println("Enviando link de recuperação para: " + cpfOuEmail);
        System.out.println("Link de recuperação: " + linkRecuperacao);

        // Aqui você poderia integrar com um serviço de envio de e-mails (ex.: JavaMail
        // API)
    }
    
private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {
    // Você pode definir o que acontece quando o usuário pressiona Enter no campo de e-mail
    btnProsseguir.doClick(); // Simula o clique no botão Prosseguir
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnProsseguir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblImgTela;
    private javax.swing.JTextField txtEmail;
    // End of variables declaration//GEN-END:variables
}
